apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-image-
spec:
  podGC:
    strategy: OnPodSuccess # delete pods when workflow is successful
  entrypoint: build-argo-image
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
  templates:
  - name: build-argo-image
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
    steps:
    - - name: mirror-image
        templateRef:
          name: flavor-image-mirror-template
          template: "{{inputs.parameters.git_ref_type}}"
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/container-argo.git
          - name: git_version
            value: "{{inputs.parameters.git_version}}"
          - name: repo_name
            value: quay.io/bradfordwagner/argo
          - name: upstream_repo
            value: "{{ item.repo }}"
          - name: upstream_repo_name_override
            value: "{{ item.name_override }}"
          - name: upstream_tag
            value: "{{ item.tag }}"
          - name: runtime_platforms
            value: "{{ item.runtime_platforms }}"
          - name: tag_suffix
            value: "-{{ item.name_override }}-{{ item.tag }}"
        withItems:
        - { repo: 'quay.io/argoproj/argocli'             , tag: 'v3.3.1' , name_override: argocli             , runtime_platforms: [linux/amd64 , linux/arm64] }
        - { repo: 'quay.io/argoproj/workflow-controller' , tag: 'v3.3.5' , name_override: workflow_controller , runtime_platforms: [linux/amd64 , linux/arm64] }

